package es.reservasvuelo.model;
// Generated 08-feb-2017 11:43:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Aerolinea generated by hbm2java
 */
@Entity
@Table(name="aerolinea"
    ,catalog="ReservaVuelos"
    , uniqueConstraints = @UniqueConstraint(columnNames="codigo") 
)
public class Aerolinea  implements java.io.Serializable {


     private int aerolineaId;
     private String codigo;
     private String nombre;
     private Set vueloGenericos = new HashSet(0);

    public Aerolinea() {
    }

	
    public Aerolinea(int aerolineaId, String codigo, String nombre) {
        this.aerolineaId = aerolineaId;
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Aerolinea(int aerolineaId, String codigo, String nombre, Set vueloGenericos) {
       this.aerolineaId = aerolineaId;
       this.codigo = codigo;
       this.nombre = nombre;
       this.vueloGenericos = vueloGenericos;
    }
   
     @Id 

    
    @Column(name="aerolinea_id", unique=true, nullable=false)
    public int getAerolineaId() {
        return this.aerolineaId;
    }
    
    public void setAerolineaId(int aerolineaId) {
        this.aerolineaId = aerolineaId;
    }

    
    @Column(name="codigo", unique=true, nullable=false, length=100)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aerolinea")
    public Set getVueloGenericos() {
        return this.vueloGenericos;
    }
    
    public void setVueloGenericos(Set vueloGenericos) {
        this.vueloGenericos = vueloGenericos;
    }




}


