package es.reservasvuelo.model;
// Generated 08-feb-2017 11:43:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Aeropuerto generated by hbm2java
 */
@Entity
@Table(name="aeropuerto"
    ,catalog="ReservaVuelos"
    , uniqueConstraints = @UniqueConstraint(columnNames="codigo") 
)
public class Aeropuerto  implements java.io.Serializable {


     private Integer aeropuertoId;
     private Ciudad ciudad;
     private String codigo;
     private String nombre;
     private int categoria;
     private Set vueloGenericos = new HashSet(0);

    public Aeropuerto() {
    }

	
    public Aeropuerto(Ciudad ciudad, String codigo, String nombre, int categoria) {
        this.ciudad = ciudad;
        this.codigo = codigo;
        this.nombre = nombre;
        this.categoria = categoria;
    }
    public Aeropuerto(Ciudad ciudad, String codigo, String nombre, int categoria, Set vueloGenericos) {
       this.ciudad = ciudad;
       this.codigo = codigo;
       this.nombre = nombre;
       this.categoria = categoria;
       this.vueloGenericos = vueloGenericos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="aeropuerto_id", unique=true, nullable=false)
    public Integer getAeropuertoId() {
        return this.aeropuertoId;
    }
    
    public void setAeropuertoId(Integer aeropuertoId) {
        this.aeropuertoId = aeropuertoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ciudad", nullable=false)
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }

    
    @Column(name="codigo", unique=true, nullable=false, length=100)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="categoria", nullable=false)
    public int getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(int categoria) {
        this.categoria = categoria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aeropuerto")
    public Set getVueloGenericos() {
        return this.vueloGenericos;
    }
    
    public void setVueloGenericos(Set vueloGenericos) {
        this.vueloGenericos = vueloGenericos;
    }




}


