package es.reservasvuelo.model;
// Generated 12-feb-2017 0:43:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Reservas generated by hbm2java
 */
@Entity
@Table(name="reservas"
    ,catalog="ReservaVuelos"
    , uniqueConstraints = @UniqueConstraint(columnNames={"vuelo_id", "tarjeta"}) 
)
public class Reservas  implements java.io.Serializable {


     private Integer reservasId;
     private Vuelo vuelo;
     private String nombre;
     private String apellidos;
     private String telefono;
     private String tarjeta;
     private double importe;

    public Reservas() {
    }

    public Reservas(Vuelo vuelo, String nombre, String apellidos, String telefono, String tarjeta, double importe) {
       this.vuelo = vuelo;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.tarjeta = tarjeta;
       this.importe = importe;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="reservas_id", unique=true, nullable=false)
    public Integer getReservasId() {
        return this.reservasId;
    }
    
    public void setReservasId(Integer reservasId) {
        this.reservasId = reservasId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vuelo_id", nullable=false)
    public Vuelo getVuelo() {
        return this.vuelo;
    }
    
    public void setVuelo(Vuelo vuelo) {
        this.vuelo = vuelo;
    }

    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidos", nullable=false, length=200)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="telefono", nullable=false, length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="tarjeta", nullable=false, length=16)
    public String getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(String tarjeta) {
        this.tarjeta = tarjeta;
    }

    
    @Column(name="importe", nullable=false, precision=22, scale=0)
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }




}


