package es.reservasvuelo.model;
// Generated 25-nov-2016 10:30:50 by Hibernate Tools 4.3.1


import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 * Actor generated by hbm2java
 */
@Named(value = "vueloGenerico")
@RequestScoped
public class VueloGenerico  implements java.io.Serializable {


     private Short nVuelo;
     private String horaSalida;
     private String horaLlegada;
     private double precio;
     private int capacidad;
     private String ordenAsiento;
     private Short aeropuerto_id;
     private Short aerolinea_id;

    public VueloGenerico() {
    }

    


}


