package es.reservasvuelo.model;
// Generated 08-feb-2017 11:43:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VueloGenerico generated by hbm2java
 */
@Entity
@Table(name="vueloGenerico"
    ,catalog="ReservaVuelos"
)
public class VueloGenerico  implements java.io.Serializable {


     private Integer nvuelo;
     private Aerolinea aerolinea;
     private Aeropuerto aeropuerto;
     private Integer horaSalida;
     private Integer horaLlegada;
     private double precio;
     private int capacidad;
     private Set vuelos = new HashSet(0);

    public VueloGenerico() {
    }

	
    public VueloGenerico(Aeropuerto aeropuerto, double precio, int capacidad) {
        this.aeropuerto = aeropuerto;
        this.precio = precio;
        this.capacidad = capacidad;
    }
    public VueloGenerico(Aerolinea aerolinea, Aeropuerto aeropuerto, Integer horaSalida, Integer horaLlegada, double precio, int capacidad, Set vuelos) {
       this.aerolinea = aerolinea;
       this.aeropuerto = aeropuerto;
       this.horaSalida = horaSalida;
       this.horaLlegada = horaLlegada;
       this.precio = precio;
       this.capacidad = capacidad;
       this.vuelos = vuelos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="nVuelo", unique=true, nullable=false)
    public Integer getNvuelo() {
        return this.nvuelo;
    }
    
    public void setNvuelo(Integer nvuelo) {
        this.nvuelo = nvuelo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aerolinea_id")
    public Aerolinea getAerolinea() {
        return this.aerolinea;
    }
    
    public void setAerolinea(Aerolinea aerolinea) {
        this.aerolinea = aerolinea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aeropuerto_id", nullable=false)
    public Aeropuerto getAeropuerto() {
        return this.aeropuerto;
    }
    
    public void setAeropuerto(Aeropuerto aeropuerto) {
        this.aeropuerto = aeropuerto;
    }

    
    @Column(name="horaSalida")
    public Integer getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Integer horaSalida) {
        this.horaSalida = horaSalida;
    }

    
    @Column(name="horaLlegada")
    public Integer getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(Integer horaLlegada) {
        this.horaLlegada = horaLlegada;
    }

    
    @Column(name="precio", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }

    
    @Column(name="capacidad", nullable=false)
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vueloGenerico")
    public Set getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set vuelos) {
        this.vuelos = vuelos;
    }




}


