package es.reservasvuelo.model;
// Generated 08-feb-2017 11:43:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Vuelo generated by hbm2java
 */
@Entity
@Table(name="vuelo"
    ,catalog="ReservaVuelos"
    , uniqueConstraints = {@UniqueConstraint(columnNames="fecha"), @UniqueConstraint(columnNames={"fecha", "nVuelo"}), @UniqueConstraint(columnNames="nVuelo")} 
)
public class Vuelo  implements java.io.Serializable {


     private Integer vueloId;
     private VueloGenerico vueloGenerico;
     private int plazasLibres;
     private Date fecha;
     private Set reservases = new HashSet(0);

    public Vuelo() {
    }

	
    public Vuelo(VueloGenerico vueloGenerico, int plazasLibres, Date fecha) {
        this.vueloGenerico = vueloGenerico;
        this.plazasLibres = plazasLibres;
        this.fecha = fecha;
    }
    public Vuelo(VueloGenerico vueloGenerico, int plazasLibres, Date fecha, Set reservases) {
       this.vueloGenerico = vueloGenerico;
       this.plazasLibres = plazasLibres;
       this.fecha = fecha;
       this.reservases = reservases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vuelo_id", unique=true, nullable=false)
    public Integer getVueloId() {
        return this.vueloId;
    }
    
    public void setVueloId(Integer vueloId) {
        this.vueloId = vueloId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nVuelo", unique=true, nullable=false)
    public VueloGenerico getVueloGenerico() {
        return this.vueloGenerico;
    }
    
    public void setVueloGenerico(VueloGenerico vueloGenerico) {
        this.vueloGenerico = vueloGenerico;
    }

    
    @Column(name="plazasLibres", nullable=false)
    public int getPlazasLibres() {
        return this.plazasLibres;
    }
    
    public void setPlazasLibres(int plazasLibres) {
        this.plazasLibres = plazasLibres;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", unique=true, nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vuelo")
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }




}


